package(default_visibility = ["//visibility:public"])

exports_files(["jsonnet.bzl"])

py_binary(
    name = "stamper",
    srcs = ["stamper.py"],
    main = "stamper.py",
    visibility = ["//visibility:public"],
)